version: "3"
services:
  rdsrecorder:
    image: golang:1.22.1-bullseye
    command: bash -c "while true; do sleep 100; done"
    volumes:
      - ./:/rdsrecorder
      - $HOME/.aws:/root/.aws
    environment:
      AWS_SDK_LOAD_CONFIG: true
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090

volumes:
    prometheus_data:
