{
 "title": "rdsrecorder",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "loki_source", "query": "loki" },
   {
    "name": "podName",
    "query": {
     "query": "label_values({namespace=\"rdsrecorder\"},pod)"
    }
   },
   { "name": "interval", "query": "5m,15m,30m,1h,2h" }
  ]
 },
 "panels": [
  {
   "title": "RDS Downloaded Logs Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rdsrecorder_downloaded_logs_total{pod=\"$podName\"}",
     "legendFormat": "downloaded_logs_total"
    }
   ]
  },
  {
   "title": "S3 Uploaded Logs Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rdsrecorder_uploaded_s3_logs_total{pod=\"$podName\"}",
     "legendFormat": "downloaded_logs_total"
    }
   ]
  },
  {
   "title": "Total Size Log Files",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rdsrecorder_uploaded_s3_size_logs_total{pod=\"$podName\"}",
     "legendFormat": "downloaded_logs_total"
    }
   ]
  },
  {
   "title": "Rate Downloaded Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(rdsrecorder_downloaded_logs_total{pod=\"$podName\"}[$interval])",
     "legendFormat": "rate_downloaded_files"
    }
   ]
  },
  {
   "title": "Rate Uploaded S3 Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(rdsrecorder_uploaded_s3_logs_total{pod=\"$podName\"}[$interval])",
     "legendFormat": "rate_uploaded_logs"
    }
   ]
  },
  {
   "title": "Pod Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{pod=\"$podName\"} |= ``"
    }
   ]
  }
 ]
}